INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (1, 'Exatas');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (2, 'Biológicas');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (3, 'Engenharias');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (4, 'Saúde');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (5, 'Socias Aplicadas');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (6, 'Humanas');
INSERT INTO AREA_CONHECIMENTO (ID,DESCRICAO) VALUES (7, 'Linguística, Letras e Artes');